name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    paths:
    - 'src/Contoso.WebApi/**'

env:
  AZURE_WEBAPP_NAME: hackwindowswebapi  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'     # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/Contoso.WebApi
    
    
    steps: 
    - uses: actions/checkout@v2
  #  - uses: azure/login@v1
  #    with:
  #      creds: ${{ secrets.DEPLOYGITHUB }}
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: echo Github Workspace
      run: echo ${{ env.GITHUB_WORKSPACE }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run:  dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/webapi' 
